name: cli_goodies
description: A simple command-line application.
version: 0.0.1
homepage: https://github.com/mah-dvlpr/cli_goodies

environment:
  sdk: '>=2.10.0 <3.0.0'

#dependencies:
#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
